name: Deploy container
description: Build, generate SBOMs, combine them, and push an OCI image

inputs:
  appname:
    description: Application name for push
    required: true
  image_name:
    description: Image name for push
    required: true
  registry_token:
    description: Token for registry push
    required: true
  badges_token:
    description: Token for badges branch
    required: false
  
  registry:
    description: Registry hostname
    required: false
    default: ghcr.io
  namespace:
    description: Registry namespace
    required: false
    default: simons-containers
  containerfile:
    description: Path to Containerfile
    required: false
    default: Containerfile
  context:
    description: Build context directory
    required: false
    default: .
  target:
    description: Optional build target
    required: false
    default: ""
  source:
    description: Path to sources.json for metadata SBOM
    required: false
    default: sources.json
  tag_latest:
    description: Whether to tag the image as latest if the current branch is the default branch
    required: false
    default: false
  suffix:
    description: Optional suffix to append to the image tag when pushing
    required: false
    default: ""

runs:
  using: composite
  steps:

    - name: Build image
      id: build
      uses: simons-containers/actions/build@main
      with:
        containerfile: ${{ inputs.containerfile }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        upload_artifact: true

    - name: Push image
      id: push
      uses: simons-containers/actions/push@main
      with:
        appname: ${{ inputs.appname }}
        image_name: ${{ inputs.image_name }}
        namespace: ${{ inputs.namespace }}
        registry: ${{ inputs.registry }}
        registry_token: ${{ inputs.registry_token }}
        tag_latest: ${{ inputs.tag_latest }}
        suffix: ${{ inputs.suffix }}

    - name: Update badges
      uses: simons-containers/actions/badges@main
      with:
        version: ${{ steps.push.outputs.version }}
        size: ${{ steps.push.outputs.size }}
        registry: ${{ inputs.registry }}
        namespace: ${{ inputs.namespace }}
        image_name: ${{ inputs.image_name }}
        registry_token: ${{ inputs.registry_token }}
        badges_token: ${{ inputs.badges_token }}

    - name: Create metadata SBOM
      uses: simons-containers/actions/create-sbom@main
      with:
        source: ${{ inputs.source }}
        destination: /tmp/sbom.cdx.json

    - name: Combine SBOMs
      uses: simons-containers/actions/combine-sboms@main
      with:
        image: image.tar
        source: ${{ inputs.source }}
        output: sbom.combined.cdx.json
        target: ${{ inputs.target }}

    - name: Attest container
      uses: actions/attest@v4
      with:
        subject-name: ${{ inputs.registry}}/${{ inputs.namespace }}/${{ inputs.image_name }}
        subject-digest: ${{ steps.build.outputs.digest }}
        sbom-path: sbom.combined.cdx.json
        push-to-registry: false

    - name: Run Grype scan
      id: grype_scan
      uses: simons-containers/actions/grype-scan@main
      with:
        source: sbom.combined.cdx.json

    - name: Badge - Critical vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: Critical
        message: ${{ steps.grype_scan.outputs.critical }}
        message-color: red
        file-name: critical.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - High vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: High
        message: ${{ steps.grype_scan.outputs.high }}
        message-color: orange
        file-name: high.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - Medium vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: Medium
        message: ${{ steps.grype_scan.outputs.medium }}
        message-color: yellow
        file-name: medium.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - Low vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: Low
        message: ${{ steps.grype_scan.outputs.low }}
        message-color: blue
        file-name: low.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - Negligible vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: Negligible
        message: ${{ steps.grype_scan.outputs.negligible }}
        message-color: lightgrey
        file-name: negligible.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - Unknown vulnerabilities
      uses: action-badges/core@0.4.1
      with:
        label: Unknown
        message: ${{ steps.grype_scan.outputs.unknown }}
        message-color: lightgrey
        file-name: unknown.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Run dive scan
      id: dive
      uses: simons-containers/actions/dive-scan@main
      with:
        image: ${{ inputs.registry}}/${{ inputs.namespace }}/${{ inputs.image_name }}:${{ steps.push.outputs.version }}

    - name: Badge - Dive wasted size
      uses: action-badges/core@0.4.1
      with:
        label: Wasted Size
        message: ${{ steps.dive.outputs.wasted }}
        message-color: blue
        file-name: wasted.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"

    - name: Badge - Dive efficiency score
      uses: action-badges/core@0.4.1
      with:
        label: Efficiency Score
        message: ${{ steps.dive.outputs.efficiency }}%
        message-color: blue
        file-name: efficiency.svg
        badge-branch: badges
        github-token: "${{ inputs.badges_token }}"
